version: '3'
services:
    web:
        build: .
        restart: always
        command: bash ./deploy/start.sh
        environment:
            - FLASK_ENV=development
        ports:
            - '5000:5000'
        volumes:
            - .:/var/www
    nginx:
        build: ./nginx/.
        restart: always
        ports:
            - '80:80'
        volumes:
            - web:/var/www
        links:
            - web
    db:
        restart: always
        image: postgres
        volumes:
            - postgres-data:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: secret
            POSTGRES_USER: flask
            POSTGRES_DB: flask_db
        ports:
            - "54324:5432"
volumes:
    web:
